<br />
<br />
<br />
<header id="topo">
    <div class="container">
        <h1>Painel </h1>
        <p class="lead">Navegue pelo menu.</p>
    </div>
</header>

<div class="container">
</div>
<script>
$(document).ready(function(){
    /*
    var json = {
                "login": "ttttttt",
                "senha": "123"
            }
    
    $.ajax({
        type: "POST",
        dataType : "json",
        url: '/api',
        data: {dados: json},
        success: function(data){
            console.log(data);
        }
    });
    */
});
</script>